apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python
    image: python:3.9.12-alpine3.15
    command:
    - sleep
    args:
    - infinity
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - infinity
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  # - name: helm
  #   image: alpine/helm:3.12.0
  #   command:
  #   - sleep
  #   args:
  #   - infinity
  - name: crane
    image: gcr.io/go-containerregistry/crane:debug
    command:
    - sleep
    args:
    - infinity
  - name: alpine
    image: alpine:3.18
    command:
    - sleep
    args:
    - infinity
  volumes:
  - name: kaniko-secret
    secret:
      secretName: harbor-credentials
      items:
      - key: .dockerconfigjson
        path: config.json
  hostAliases:
  - ip: "172.18.0.50"
    hostnames:
    - "gitea.localhost.com"  
  securityContext:
    # ubuntu runs as root by default, it is recommended or even mandatory in some environments (such as pod security admission "restricted") to run as a non-root user.
    runAsUser